In [1]:
import pandas as pd
import numpy as np

In [2]:
enem_sp = pd.read_csv('/Users/paull/OneDrive/Área de Trabalho/LEONARDO/python/jupyter/enem_2019_tratado.csv',
                     sep = ',', encoding = 'iso-8859-1')

enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Campinas']

In [3]:
enem_campinas.shape

(13198, 24)

In [4]:
np.random.seed(2)
inicio = np.random.choice(10,1)

In [5]:
amostra2 = np.arange(inicio,13198,100)
amostra2

array([    8,   108,   208,   308,   408,   508,   608,   708,   808,
         908,  1008,  1108,  1208,  1308,  1408,  1508,  1608,  1708,
        1808,  1908,  2008,  2108,  2208,  2308,  2408,  2508,  2608,
        2708,  2808,  2908,  3008,  3108,  3208,  3308,  3408,  3508,
        3608,  3708,  3808,  3908,  4008,  4108,  4208,  4308,  4408,
        4508,  4608,  4708,  4808,  4908,  5008,  5108,  5208,  5308,
        5408,  5508,  5608,  5708,  5808,  5908,  6008,  6108,  6208,
        6308,  6408,  6508,  6608,  6708,  6808,  6908,  7008,  7108,
        7208,  7308,  7408,  7508,  7608,  7708,  7808,  7908,  8008,
        8108,  8208,  8308,  8408,  8508,  8608,  8708,  8808,  8908,
        9008,  9108,  9208,  9308,  9408,  9508,  9608,  9708,  9808,
        9908, 10008, 10108, 10208, 10308, 10408, 10508, 10608, 10708,
       10808, 10908, 11008, 11108, 11208, 11308, 11408, 11508, 11608,
       11708, 11808, 11908, 12008, 12108, 12208, 12308, 12408, 12508,
       12608, 12708,

a variavel 'amostra 2' escolhe um numero aleatório de 1 até 10 (definido pela variável ínicio e pega os valores de 100 em 100 para definir uma amostra que vai até o 13198º candidato

In [6]:
amostra_sistematica = enem_campinas.iloc[amostra2,:]
amostra_sistematica

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  IDADE SEXO  TP_ESTADO_CIVIL  \
401        1,90E+11                Campinas     18    F                1   
5079       1,90E+11                Campinas     18    F                1   
9218       1,90E+11                Campinas     19    F                1   
13685      1,90E+11                Campinas     20    M                1   
18239      1,90E+11                Campinas     20    M                1   
...             ...                     ...    ...  ...              ...   
481894     1,90E+11                Campinas     34    M                1   
485805     1,90E+11                Campinas     16    F                1   
488958     1,90E+11                Campinas     19    F                1   
492626     1,90E+11                Campinas     21    M                1   
496410     1,90E+11                Campinas     19    M                1   

          RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA   CO_ESCOLA  \
401     branca                 1                1  não_respondeu         NaN   
5079    branca                 1                2        pública  35018855.0   
9218    branca                 1                1  não_respondeu         NaN   
13685    parda                 1                1  não_respondeu         NaN   
18239   branca                 1                1  não_respondeu         NaN   
...        ...               ...              ...            ...         ...   
481894   parda                 1                1  não_respondeu         NaN   
485805  branca                 1                2        pública  35039901.0   
488958  branca                 1                1  não_respondeu         NaN   
492626  branca                 1                1  não_respondeu         NaN   
496410   preta                 1                1  não_respondeu         NaN   

        ... NOTA_MT  TP_LINGUA  TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  \
401     ...    68.6     Inglês                1.0  160.0  160.0  180.0  160.0   
5079    ...   419.9     Inglês                1.0  140.0  120.0  120.0  120.0   
9218    ...   617.1     Inglês                1.0  120.0  120.0  120.0  120.0   
13685   ...   576.4     Inglês                1.0  160.0  200.0  180.0  200.0   
18239   ...   796.2     Inglês                1.0  160.0  200.0  200.0  200.0   
...     ...     ...        ...                ...    ...    ...    ...    ...   
481894  ...   932.1     Inglês                1.0  140.0  120.0  160.0  160.0   
485805  ...   441.6     Inglês                1.0  120.0  120.0  100.0  120.0   
488958  ...   492.9     Inglês                1.0  160.0  120.0  140.0  120.0   
492626  ...    51.1     Inglês                1.0  120.0  120.0  120.0  100.0   
496410  ...   404.4     Inglês                1.0  100.0   80.0   80.0   80.0   

        COMP5  NOTA_REDACAO  INTERNET  
401     200.0         860.0       Sim  
5079    140.0         640.0       Sim  
9218    120.0         600.0       Sim  
13685   180.0         920.0       Sim  
18239   200.0         960.0       Sim  
...       ...           ...       ...  
481894  160.0         740.0       Sim  
485805    0.0         460.0       Sim  
488958  140.0         680.0       Sim  
492626    0.0         460.0       Sim  
496410   40.0         380.0       Sim  

[132 rows x 24 columns]

na tabela de dados enem campinas é buscado os candidatos de índice (iloc) pertencente a amostra 2

# outra maneira

In [10]:
np.random.seed(3)
inicio = np.random.choice(10, 1)
passo = np.random.randint(100, 150, 1) # é criada a varíavel passo que é aleatorio, é escolhido um numero entre 50 e 150
inicio

array([8])

In [11]:
passo

array([103])

In [14]:
amostra2 = np.arange(inicio, 13198, passo)
amostra2

array([    8,   111,   214,   317,   420,   523,   626,   729,   832,
         935,  1038,  1141,  1244,  1347,  1450,  1553,  1656,  1759,
        1862,  1965,  2068,  2171,  2274,  2377,  2480,  2583,  2686,
        2789,  2892,  2995,  3098,  3201,  3304,  3407,  3510,  3613,
        3716,  3819,  3922,  4025,  4128,  4231,  4334,  4437,  4540,
        4643,  4746,  4849,  4952,  5055,  5158,  5261,  5364,  5467,
        5570,  5673,  5776,  5879,  5982,  6085,  6188,  6291,  6394,
        6497,  6600,  6703,  6806,  6909,  7012,  7115,  7218,  7321,
        7424,  7527,  7630,  7733,  7836,  7939,  8042,  8145,  8248,
        8351,  8454,  8557,  8660,  8763,  8866,  8969,  9072,  9175,
        9278,  9381,  9484,  9587,  9690,  9793,  9896,  9999, 10102,
       10205, 10308, 10411, 10514, 10617, 10720, 10823, 10926, 11029,
       11132, 11235, 11338, 11441, 11544, 11647, 11750, 11853, 11956,
       12059, 12162, 12265, 12368, 12471, 12574, 12677, 12780, 12883,
       12986, 13089,

In [15]:
amostra2_camp = enem_campinas.iloc[amostra2,:]

In [16]:
amostra2_camp

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  IDADE SEXO  TP_ESTADO_CIVIL  \
401        1,90E+11                Campinas     18    F                1   
5229       1,90E+11                Campinas     18    F                1   
9455       1,90E+11                Campinas     17    F                1   
13926      1,90E+11                Campinas     21    M                1   
18554      1,90E+11                Campinas     17    M                1   
...             ...                     ...    ...  ...              ...   
484690     1,90E+11                Campinas     17    M                1   
488340     1,90E+11                Campinas     19    F                1   
491708     1,90E+11                Campinas     19    F                1   
495779     1,90E+11                Campinas     20    M                1   
499691     1,90E+11                Campinas     17    F                1   

          RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA   CO_ESCOLA  \
401     branca                 1                1  não_respondeu         NaN   
5229    branca                 1                1  não_respondeu         NaN   
9455    branca                 1                2        pública         NaN   
13926    preta                 1                1  não_respondeu         NaN   
18554    parda                 1                2        pública         NaN   
...        ...               ...              ...            ...         ...   
484690   parda                 1                2        pública  35018788.0   
488340  branca                 1                1  não_respondeu         NaN   
491708  branca                 1                1  não_respondeu         NaN   
495779   preta                 1                1  não_respondeu         NaN   
499691   preta                 1                2        pública  35018089.0   

        ... NOTA_MT  TP_LINGUA  TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  \
401     ...    68.6     Inglês                1.0  160.0  160.0  180.0  160.0   
5229    ...   606.2     Inglês                1.0  140.0  120.0  160.0  160.0   
9455    ...   620.6     Inglês                1.0  140.0  140.0  140.0  120.0   
13926   ...   545.6     Inglês                1.0  160.0  160.0  120.0  120.0   
18554   ...   701.5     Inglês                1.0  160.0  200.0  180.0  160.0   
...     ...     ...        ...                ...    ...    ...    ...    ...   
484690  ...    54.1     Inglês                1.0  100.0  100.0  100.0  120.0   
488340  ...   542.3   Espanhol                1.0  120.0  120.0  140.0  120.0   
491708  ...   423.4     Inglês                1.0  120.0  120.0  120.0  120.0   
495779  ...   465.8     Inglês                1.0  120.0   40.0   40.0  120.0   
499691  ...   770.3     Inglês                1.0  120.0  120.0  120.0  160.0   

        COMP5  NOTA_REDACAO  INTERNET  
401     200.0         860.0       Sim  
5229     80.0         660.0       Sim  
9455    120.0         660.0       Não  
13926   140.0         700.0       Não  
18554   200.0         900.0       Sim  
...       ...           ...       ...  
484690   80.0         500.0       Sim  
488340   80.0         580.0       Sim  
491708  120.0         600.0       Sim  
495779    0.0         320.0       Sim  
499691   80.0         600.0       Sim  

[129 rows x 24 columns]