In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt
import statsmodels
from statsmodels.stats.diagnostic import lilliefors
from statsmodels.stats.weightstats import ztest
import plotly.express as px
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
from sklearn.linear_model import LinearRegression

enem_sp = pd.read_csv('/Users/paull/OneDrive/Área de Trabalho/LEONARDO/python/jupyter/enem_2019_tratado.csv',
                     sep = ',', encoding = 'iso-8859-1')


colegiox = enem_sp.loc[enem_sp.CO_ESCOLA == 35017632.0]
nota_final = ['NOTA_CN', 'NOTA_CH','NOTA_LC','NOTA_REDACAO','NOTA_MT']

colegiox['nota_final'] = (colegiox[nota_final].mean(axis = 1))
nota_colegiox = colegiox[['NOTA_CN','NOTA_MT','NOTA_LC','NOTA_CH','NOTA_REDACAO','nota_final']]

regressao = smf.ols('nota_final ~ NOTA_REDACAO', data = nota_colegiox).fit()

coefs = pd.DataFrame(regressao.params)
coefs.colums = ['Coeficientes']

residuos = regressao.resid

C:\Users\paull\AppData\Local\Temp\ipykernel_27564\1362875431.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colegiox['nota_final'] = (colegiox[nota_final].mean(axis = 1))
C:\Users\paull\AppData\Local\Temp\ipykernel_27564\1362875431.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  coefs.colums = ['Coeficientes']


# Regressão com o SKlearn

In [3]:
nota_colegiox.head()

NOTA_CN  NOTA_MT  NOTA_LC  NOTA_CH  NOTA_REDACAO  nota_final
37     46.3    537.1    557.3    447.2         340.0      385.58
44    505.9    451.9    529.8    534.5         720.0      548.42
52    449.4    506.4     45.8    436.4         560.0      399.60
65    468.6     59.5    576.6    606.1         520.0      446.16
79    414.3    510.6     49.5    553.7         640.0      433.62

In [2]:
x = nota_colegiox.iloc[:, 4].values
y = nota_colegiox.iloc[:, 5].values

In [4]:
correlacao2 = np.corrcoef (x,y)
correlacao2

array([[1.        , 0.55122032],
       [0.55122032, 1.        ]])

In [5]:
x = x.reshape(-1,1) # transformando em matriz

In [8]:
regressao2 = LinearRegression()
regressao2.fit(x,y)

LinearRegression()

In [11]:
regressao2.intercept_ #coeficiente angular

251.6788552750226

In [12]:
regressao2.coef_

array([0.36274917])

In [13]:
# coeficiente de determinação
regressao2.score(x,y)

0.30384384379611706

In [14]:
previsoes = regressao2.predict(x)
previsoes

array([375.01357169, 512.85825473, 454.81838819, 440.30842155,
       483.83832146, 382.268555  , 498.3482881 , 454.81838819,
       469.32835482, 440.30842155, 447.56340487, 433.05343823,
       491.09330478, 353.24862173, 440.30842155, 411.28848828,
       425.79845491, 440.30842155, 425.79845491, 447.56340487,
       491.09330478, 491.09330478, 447.56340487, 491.09330478,
       440.30842155, 469.32835482, 469.32835482, 396.77852164,
       447.56340487, 425.79845491, 396.77852164, 469.32835482,
       454.81838819, 433.05343823, 440.30842155, 353.24862173,
       469.32835482, 447.56340487, 440.30842155, 396.77852164,
       476.58333814])

In [16]:
previsao = regressao2.predict([[330]])
previsao

array([371.38608003])